# Generated by Django 3.2.13 on 2023-09-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('nutriente', models.CharField(max_length=25)),
                ('cor', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Faixas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arte_marcial', models.CharField(max_length=25)),
                ('cor', models.CharField(max_length=25)),
                ('requer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Finalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arte_marcial', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=50)),
                ('pontos', models.IntegerField()),
            ],
        ),
    ]
